#!/usr/bin/bash
# Configures nginx to return a custom HTTP response header

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom configuration file
sudo bash -c 'cat > /etc/nginx/sites-available/default' << EOF
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm;


        server_name _;

        location / {
                try_files $uri $uri/ =404;
                add_header X-Served-By $(hostname);
        }
}
EOF

# Restart nginx
sudo systemctl restart nginx
