#!/usr/bin/env bash
# Display Best School for 8 times and a Hi on the 8th time.

count=0

while [ $count -lt 10 ]; do
	
	if  [ $count -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi

	count=$((count + 1))
done
