#!/usr/bin/env bash
# uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.

server_address="54.161.241.44"
private_key="~/.ssh/school"

remote_user="ubuntu"

ssh -i "$private_key" "$remote_user"@"$server_address" 
